- id: '1763956335966'
  alias: Sleep
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Stop charging
    - Turn off charging
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id:
      - switch.45w_sonoff_s31_relay
      - switch.desk_lamp_sonoff_s31_relay
    data: {}
  mode: single
- id: '1763956518010'
  alias: Sleep
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Sleep
    - Good night
    id: voice
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.desk_lamp
    data: {}
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.sleep
  mode: single
- id: '1763956737552'
  alias: Never mind
  description: ''
  triggers:
  - trigger: conversation
    command: Never mind
  conditions: []
  actions: []
  mode: single
- id: '1777756584397'
  alias: Sound on
  description: ''
  triggers:
  - trigger: time
    at: '22:30:00'
    weekday:
    - sun
    - mon
    - sat
    - tue
    - wed
    - thu
    - fri
  - trigger: time
    at: 07:30:00
    weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
  conditions: []
  actions:
  - action: timer.cancel
    metadata: {}
    target:
      entity_id: timer.stop_noise
    data: {}
  - action: shell_command.start_noise
    metadata: {}
    data: {}
  - action: timer.start
    metadata: {}
    target:
      entity_id: timer.stop_noise
    data:
      duration:
        hours: 0
        minutes: 0
        seconds: 10
  mode: single
- id: '1777756818348'
  alias: Stop noise
  description: ''
  triggers:
  - trigger: event
    event_type: timer.finished
    event_data:
      entity_id: timer.stop_noise
  conditions: []
  actions:
  - action: timer.cancel
    metadata: {}
    target:
      entity_id: timer.stop_noise
    data: {}
  - action: shell_command.stop_noise
    metadata: {}
    data: {}
  mode: single
