- id: '1762826642637'
  alias: 45W turn on
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.sonoff_s31_sonoff_s31_relay
  mode: single
- id: '1763878563135'
  alias: 'Charge phone '
  description: ''
  triggers:
  - trigger: time
    at: 06:00:00
  conditions: []
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.sonoff_s312_sonoff_s31_relay
  mode: single
- id: '1763956335966'
  alias: Sleep
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Stop charging
    - Turn off charging
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.45w_sonoff_s31_relay
    data: {}
  - action: switch.turn_off
    metadata: {}
    target:
      entity_id: switch.desk_lamp_sonoff_s31_relay
    data: {}
  mode: single
- id: '1763956518010'
  alias: Sleep
  description: ''
  triggers:
  - trigger: conversation
    command:
    - Sleep
    - Good night
    id: voice
  conditions: []
  actions:
  - action: light.turn_off
    metadata: {}
    target:
      entity_id: light.desk_lamp
    data: {}
  - action: automation.trigger
    metadata: {}
    data:
      skip_condition: true
    target:
      entity_id: automation.sleep
  mode: single
- id: '1763956737552'
  alias: Never mind
  description: ''
  triggers:
  - trigger: conversation
    command: Never mind
  conditions: []
  actions: []
  mode: single
