name: home-server-network

networks:
  # frontend:
  #   driver: bridge
  #   driver_opts:
  #     com.docker.network.bridge.name: "frontend0"
  #     com.docker.network.bridge.enable_icc: "false"
  photos_frontend:
    external: true
  # traefik:
    # driver: bridge
    # driver_opts:
      # com.docker.network.bridge.name: "traefik0"

services:
  traefik:
    image: traefik:v3.2
    command:
      - "--providers.docker=true"
      # - "--api.insecure=true" # Enable Traefik dashboard (for testing, not recommended in production)
      - "--log.level=DEBUG"
    ports:
      - "80:80" # Expose HTTP
      - "443:443"
      # - "8080:8080" # debugging
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
    networks:
      - photos_frontend 
