services:
  tailscale:
    image: tailscale/tailscale:latest
    env_file:
      - .env
    environment:
      TS_SERVE_CONFIG: "/serve-config.json"
      TS_STATE_DIR: "/var/lib/tailscale"
    volumes:
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - ${PWD}/serve-config.json:/serve-config.json
    cap_add:
      - net_admin
      - sys_module
