services:
  tailscale:
    extends:
      file: ../tailscale.yaml
      service: tailscale
    hostname: anki
  server:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      args: 
        ANKI_VERSION: 24.11
    network_mode: service:tailscale
