networks:
  gitea:
    external: false

services:
  tailscale:
    extends:
      file: ../tailscale.yaml
      service: tailscale
    environment:
      TS_HOSTNAME: gitea 
      TS_AUTH_KEY: ${TS_AUTHKEY} 
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS}
    init: true
    restart: unless-stopped
    networks:
      - gitea
  server:
    image: docker.gitea.com/gitea:1.24.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: service:tailscale
