name: Feature Request
description: For feature requests related to this Docker image only.
title: '[Feature]: '
assignees:
  - mbentley
body:
  - type: markdown
    attributes:
      value: |
        ## Read Me First!

        Thanks for using my image! Hopefully it's helpful to you. You are about to report a bug you found related to the packaging or function of this Docker image, not the software itself. If you have a problem with the software that is not related to this Docker image, check out the [Samba mailing lists](https://www.samba.org/samba/archives.html). If you're not sure if it is a problem with the Docker image or the software, file an issue here and I can assist in determining where the responsibility lies. Apple has changed how Time Machine functions behind the scenes a number of times and it requires samba configuration changes to resolve but a lack of documentation makes it difficult to track down.
  - type: textarea
    id: feature-problem
    attributes:
      label: What problem are you looking to solve?
      description: |
        A clear and concise description of what the problem or challenge is that you'd like to be addressed.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution that you have in mind
      description: |
        A clear and concise description of what you want to happen or a proposed method to solving the problem. If you have expectations around how the problem would be solved from a user experience perspective, add that information here.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature here.
    validations:
      required: false
