services:
  tailscale:
    extends:
      file: ../tailscale.yaml
      service: tailscale
    hostname: projects
  youtrack:
    image: docker.io/jetbrains/youtrack:2025.1.76253
    volumes:
      - ./data:/opt/youtrack/data
      - ./conf:/opt/youtrack/conf
      - ./logs:/opt/youtrack/logs
      - ./backups:/opt/youtrack/backups
    restart: unless-stopped
    network_mode: service:tailscale
