services:
  esphome:
    image: ghcr.io/esphome/esphome:${VERSION}
    volumes:
      - /path/to/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    env_file: 
      - .env
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
