services:
  tailscale:
    image: tailscale/tailscale:latest
    environment:
      TS_SERVE_CONFIG: "/serve-config.json"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_AUTH_KEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: ${TS_EXTRA_ARGS}
    volumes:
      - ${SSD_DATA_LOC:?error}/${COMPOSE_PROJECT_NAME}/tailscale/state:/var/lib/tailscale
      - ${PWD}/serve-config.json:/serve-config.json
    cap_add:
      - net_admin
      - sys_module
