services:
  tailscale:
    extends:
      file: ../../shared/tailscale.yaml
      service: tailscale
    hostname: syncthing
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - STGUIADDRESS=
    env_file:
      - .env
    volumes:
      - ${SSD_DATA_LOC:?error}/${COMPOSE_PROJECT_NAME}/config:/var/syncthing/config
      - ${OBSIDIAN_LOCATION}:/var/syncthing/obsidian
    network_mode:
      service:tailscale
    restart: unless-stopped
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3