networks:
  gitea:
    external: false

services:
  tailscale:
    extends:
      file: ../../shared/tailscale.yaml
      service: tailscale
    hostname: gitea
    networks:
      - gitea
  server:
    image: docker.gitea.com/gitea:1.25.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__indexer__REPO_INDEXER_ENABLED=true
      - GITEA__indexer__REPO_INDEXER_PATH=indexers/repos.bleve
      - GITEA__indexer__MAX_FILE_SIZE=1048576  # Max file size to index (1MB)
      - GITEA__indexer__REPO_INDEXER_INCLUDE=  # Glob patterns to include
      - GITEA__indexer__REPO_INDEXER_EXCLUDE=resources/bin/** # Glob patterns to exclude
    restart: always
    volumes:
      - ${SSD_DATA_LOC:?error}/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: 
      service:tailscale
  
  runner:
    image: gitea/runner:nightly
    container_name: gitea-runner
    env_file:
      - .env
    environment:
      GITEA_INSTANCE_URL: https://gitea.${TAILNET}
      GITEA_RUNNER_NAME: local-runner
    networks:
      - gitea
    volumes:
      - ${SSD_DATA_LOC:?error}/gitea-runner:/data
      # - ./config.yaml:/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
